### ISSUE TITLE
from ellipsoidal to utm and back

### ISSUE THREAD

**Issue by xanthospap** [DSOlab/StrainTool#1]
Transforming ellipsoidal to UTM coordinates and back is erroneous; see the test case in `pystrain/geodesy/utm.py`. Seems that there is a problem (at least) with negative longtitudes.

**Comment by demanasta** [comment]
The problem is with negative latitudes (not longitudes!)
At function `utm2ell`, should be defined if utm coordinates (N,E) is in the northern or southern hemisphere.
On line 18,  `if zone < 0:` , zone is always greater than zero!!
