### ISSUE TITLE
Multithreading is different between Linux and Windows

### ISSUE THREAD

**Issue by demanasta** [DSOlab/StrainTool#59]
**Description**
multicore option on Windows returns error. Windows not use [fork()](https://en.wikipedia.org/wiki/Fork_(system_call)) system, global variables not working.

**To Reproduce**
1.Run StrainTensor.py with --multicore option on Windows System
2. error:
`  File "C:\Users\diman\gh_projects\StrainTool\bin\StrainTensor.py", line 109, in compute__
    N, E, ZN, _ = ell2utm(clat, clon, Ellipsoid("wgs84"), utm_zone)
NameError: global name 'utm_zone' is not defined`

**Desktop:**
 - OS: Windows 10
 - Python: 2.7
 - GMT: 5.2.1
 - StrainTool:  v1.0-rc5.1 (dev-danast branch)

**Comment by xanthospap** [comment]
Introduced possible fix:
`utm_zone` in function `compute__` is now a local variable. `utm_zone` is passed in as `utmzone` from `__main__`.
Changes introduced only in `bin/StrainTensor.py` file.
