### ISSUE TITLE
Output files

### ISSUE THREAD

**Issue by demanasta** [DSOlab/StrainTool#6]

**Comment by demanasta** [comment]
Two output files:
1. station_info.dat ... coords and velocities af all stations used
2. strain_info.dat ... all strain rate parametes

**Comment by demanasta** [comment]
final columns
add units of each column

**Comment by demanasta** [comment]
outputs modified...
Add..
3. param_info.dat parameters of model output

**Comment by xanthospap** [comment]
I am on to it!

**Comment by demanasta** [comment]
statistics output
