### ISSUE TITLE
Bug with Multiple UMT zones and the veis method

### ISSUE THREAD

**Issue by csboucher** [DSOlab/StrainTool#73]
**Describe the bug**
The "veis" method doesn't work for multiple UMT zones

**To Reproduce**
1) Run straintool with the data file with the --method=veis

[Mid_EARS_vel.txt](https://github.com/DSOlab/StrainTool/files/7571965/Mid_EARS_vel.txt)
2)get error of UMT zoning

**Expected behavior**
I expect calculation of delaunay triangles and strain rate tensor for the veis method

**Screenshots**
![Screen Shot 2021-11-19 at 10 52 04 AM (2)](https://user-images.githubusercontent.com/87994253/142668835-c7116094-4e6d-4e0e-96a2-d7c36f318f1b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Python: [e.g. 2.7]
 - GMT: [e.g. 5.2.1]
 - StrainTool: [e.g. v1.0-beta4.0]

**Additional context**
The code was changed a few months ago to allow for multiple umt zones with the shen method but I don't know if it was changed for the veis method. Thank you!

**Comment by xanthospap** [comment]
Dear @csboucher ,

sorry for our  late reply; we will look into it and let you know the next couple of days.
regards,
Xanthos

**Comment by demanasta** [comment]
check new release v1.1
