### ISSUE TITLE
Add the main article to the project

### ISSUE THREAD

**Issue by KarineTeran** [DSOlab/StrainTool#74]
Hello,

I would like to congratulate on their project. However, I would rather have access to the next article, because I think It is very important to understand better the methodology. 

Anastasiou D., Ganas A., Legrand J., Bruyninx C., Papanikolaou X., Tsironi V. and Kapetanidis V. (2019). Tectonic strain distribution over Europe from EPN data. EGU General Assembly 2019, Geophysical Research Abstracts, Vol. 21, EGU2019-17744-1

If this is not possible, I would like to share me this article to my email.

Thank you.

**Comment by suribabud** [comment]
Please forward the above publication to suribabu.9396@gmail.com

Thanks.
