### ISSUE TITLE
straintool

### ISSUE THREAD

**Issue by shubham-rajewar** [DSOlab/StrainTool#75]
In DSOlab-StrainTool-e1d4f4f tool version 1.0
the gmt script for extracting dextral sinistral shear strain is given as below:
"# plot strain rates
  awk 'NR > 2 {print $2,$1,$19,0,$21-45+90}' $pth2strinfo \
  | gmt psvelo  -Jm $range -Sx${STRSC} -L -A.1p+e -Gred -W1.5p,red \
        -O -K -V${VRBLEVM} >> $outfile
>>according to the above command, it is used to extract data of dextral component in this version of tool but in recent version '1.0-r1' this command is looks like this:
"# plot strain rates
  # dextral 
  awk 'NR > 2 {print $2,$1,0,$19,$21-45+90}' $pth2strinfo \
  | gmt psvelo  -Jm $range -Sx${STRSC} -L -A.1p+e -Gred -W1.5p,red \
        -O -K -V${VRBLEVM} >> $outfile
both AWK command are different. please clarify the changes made in this command so we can use corrected command,

**Comment by demanasta** [comment]
recent version '1.0-r1'  is the correct command.
For the command psvelo and switch Sx azimuth refers to the second  axe.
Checkout the GMT tutorial [gmt-psvelo](https://docs.generic-mapping-tools.org/latest/supplements/geodesy/psvelo.html#required-arguments )
