### ISSUE TITLE
unable to reproduce the test

### ISSUE THREAD

**Issue by mmetois** [DSOlab/StrainTool#76]
**Describe the bug**
Get much lower uncertainties than expected running the example (/5) for each component of strain rate or velocity. 

**To Reproduce**
I have installed correctly the soft with python 3.6 (not working with 3.11 config) and tried the example (CNRS_midas.vel is not in the git directory directly, I got it from the DSOlab-StrainTool-9fa7ae7 repository and remove redundant stations). 
Run the suggested test ./StrainTensor.py -i ../data/CNRS_midas.vel -r 18.75/30.25/32.75/42.25 --x-grid-step=0.5 --y-grid-step=0.5 --dmin=1 --dmax=500 --dstep=1 --Wt=24 -c -g

**Expected behavior**
should get something like : 
Latitude  Longtitude     vx+dvx          vy+dvy           w+dw          exx+dexx        exy+dexy        eyy+deyy       emax+demax      emin+demin       shr+dshr        azi+dazi      dilat+ddilat   sec. invariant 
 36.00000  23.50000    +7.2    +5.4   -11.8    +4.6    +5.3   +26.9   +14.5   +48.1   +12.7   +26.9   +32.3   +33.3   +38.8   +42.0    +7.9   +38.1   +15.5   +27.4   +27.5    +0.9   +46.8   +58.5   +37.6
 36.00000  24.00000    +7.9    +5.4   -11.5    +4.6    +6.4   +23.6    +8.9   +43.3    +9.8   +23.6   +32.0   +28.5   +35.6   +32.6    +5.3   +38.8   +15.2   +24.7   +20.2    +0.8   +40.9   +51.9   +34.6

and got : 
Latitude  Longtitude     vx+dvx          vy+dvy           w+dw          exx+dexx        exy+dexy        eyy+deyy       emax+demax      emin+demin       shr+dshr        azi+dazi      dilat+ddilat   sec. invariant+dsec inv.
 36.00000  23.50000    +7.2     0.9   -11.8     0.7    +0.3     0.2   +15.0     7.8   +12.9     4.4   +32.1     5.3   +39.0     6.8    +8.1     6.2   +15.5     4.4   +28.2     0.1   +47.1     9.5   +39.8     6.9
 36.00000  24.00000    +7.9     0.9   -11.5     0.7    +0.3     0.2    +9.3     7.1   +10.1     3.8   +31.9     4.6   +35.7     5.3    +5.4     6.3   +15.1     4.0   +20.9     0.1   +41.2     8.4   +36.2     5.3

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Python: 3.6.3
 - GMT: whatever.
 - StrainTool: master

**Additional context**

**Comment by ditafaith** [comment]
Hi @demanasta 
I am not sure this issue has been solved or no, but I didn't find data/CNRS_midas.vel file, then we can't follow given tutorial.

**Comment by demanasta** [comment]
@ditafaith @mmetois 
we are to develop new test cases. A new release with bugs fixed will be available in a few weeks.
Please be patient, StrainTool is an open-source project and most of the maintenance is part of our free time.

**Comment by ditafaith** [comment]
I am sorry and thank you for taking care of this matters @demanasta

**Comment by demanasta** [comment]
A couple of validation tests will be available in the new release v1.1 
this issue will be closed
Thank you for your contribution
