### ISSUE TITLE
Problem when the grid cover the longitude 0

### ISSUE THREAD

**Issue by pvernant** [DSOlab/StrainTool#77]
the -r or --region option leads to error when set over longitude 0. 

Example : -r -9/15/34/58

The code returns :
usage: StrainTensor.py [-h] -i INPUT_FILE [--x-grid-step X_GRID_STEP] [--y-grid-step Y_GRID_STEP] [-m METHOD] [-r REGION]
                       [-c] [-b] [--max-beta-angle MAX_BETA_ANGLE] [-t WEIGHTING_FUNCTION] [--Wt Wt] [--dmin D_MIN]
                       [--dmax D_MAX] [--dstep D_STEP] [--d-param D_PARAMETER] [-g] [--verbose] [--multicore] [-v]
StrainTensor.py: error: argument -r/--region: expected one argument

**Comment by xanthospap** [comment]
Dear Mr. Vernant,

thank you for reporting this bug. We are looking into it and will get back
to you as soon as possible.
Always glad to see people working with the software.

Best regards,
Xanthos

**Comment by demanasta** [comment]
Dear @pvernant 

working on this project again for the next version, we are in the process of debugging the previous releases.
As for the problem with the change of longitude when passing through zero, it has actually been solved. 

The debugging and development of the code are done in branch  [dev11](https://github.com/DSOlab/StrainTool/tree/dev11) so you can confirm that the specific issue has been resolved.

Thank you again for the feedback.
DA
